// frontend-react/components/Footer/FooterBase.js
const FooterBase = () => (
  <footer>
    <p className="p--small"><i>A Latin Dictionary Founded on Andrews' edition of Freund's Latin dictionary revised, enlarged, and in great part rewritten by Charlton T. Lewis, Ph.D. and Charles Short, LL.D.</i> provided under a CC BY-SA license by Perseus Digital Library, <a href="http://www.perseus.tufts.edu" target="_blank">http://www.perseus.tufts.edu</a>, with funding from The National Endowment for the Humanities.
Data accessed from <a href="https://github.com/PerseusDL/lexica/" target="_blank">https://github.com/PerseusDL/lexica/</a> on March, 17, 2020.</p>
    <p>English-to-Latin stem dataset derived from the works of <a href="https://github.com/lukehollis" target="_blank">Luke Hollis</a>, <a href="https://github.com/dsanson" target="_blank">David Sanson</a>, and ultimately <a href="http://archives.nd.edu/words.html" target="_blank">Whitaker's Words</a> by Colonel William Whitaker.</p>
  </footer>
);

export default FooterBase;

// frontend/components/Footer/FooterBase.vue
<template>
  <footer class="layout__footer">
    <p class="p--small"><i>A Latin Dictionary Founded on Andrews' edition of Freund's Latin dictionary revised, enlarged, and in great part rewritten by Charlton T. Lewis, Ph.D. and Charles Short, LL.D.</i> provided under a CC BY-SA license by Perseus Digital Library, <a href="http://www.perseus.tufts.edu" target="_blank">http://www.perseus.tufts.edu</a>, with funding from The National Endowment for the Humanities.
Data accessed from <a href="https://github.com/PerseusDL/lexica/" target="_blank">https://github.com/PerseusDL/lexica/</a> on March, 17, 2020.</p>
    <p>English-to-Latin stem dataset derived from the works of <a href="https://github.com/lukehollis" target="_blank">Luke Hollis</a>, <a href="https://github.com/dsanson" target="_blank">David Sanson</a>, and ultimately <a href="http://archives.nd.edu/words.html" target="_blank">Whitaker's Words</a> by Colonel William Whitaker.</p>
  </footer>
</template>

<style lang="scss" scoped="true">
footer {
  padding-bottom: $spacer-2;
  padding-top: $spacer-2;
}
p {
  font-size: $font-size-5;
}
</style>
